spring:
   jackson:
      time-zone: GMT+7
      serialization.write-dates-as-timestamps: false

   jpa:
      hibernate:
         ddl-auto: update

   datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      platform: h2
    
rest:
   version: 1.0
   uri: /api/v${rest.version}
   auth.uri: /auth/v${rest.version}

com.senomas:
   http-logger:
      order: 0
      path:
         "/": BASIC
         "/v2/api-docs": OFF
         "/swagger-": OFF
         "/configuration/": OFF
         "/api/": ALL
   web:
      resolver:
         script:
            - "/app/lib/**/*.js"
            - "/app/**/app.js"
         css:
            - "/webjars/**/*.css"

